[package]
name = "proka-exec"
version = "0.6.1"
edition = "2024"
authors = ["zhangxuan2011 <zx20110412@outlook.com>"]
description = "The proka executable definitions and utilities"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/RainSTR-Studio/proka-exec"

[dependencies]
bitflags = { version = "2.13.1", features = ["bytemuck"] }
bytemuck = { version = "1.25.2", features = ["derive"] }

[features]
default = ["alloc"]
alloc = []
